file: Support macos for non-overwrite renaming
cdown/exifrename pull request #96
Opened 2024-11-02 06:15 UTC by stanaka

Add macos support for renaming without "overwrite" option.

2024-11-03 07:45 UTC, cdown requested changes
This looks great, thanks. Maybe there's some opportunity for refactoring here, but it needs some thinking about anyway, so let's leave that for now.

Only one minor comment to address, and you need to run `cargo fmt`, then I'll merge :-)

2024-11-03 07:45 UTC, cdown commented on src/file.rs
>      if !overwrite {
For the die!() below, change it to:

```rust
die!("Overwrite-free rename not implemented on this operating system. Use --overwrite.");
```

2024-11-03 12:56 UTC, stanaka commented
@cdown Thank you for the comment!
I added commits to address them. Please take a look on it.

2024-11-04 05:57 UTC, cdown commented
Thank you! I added integration tests for overwrite/non-overwrite in 05ff1b046d04922c2292981484309b30754d8e0f, so there were conflicts. I've resolved the conflicts and tested that Mac passes the integration tests (see https://github.com/cdown/exifrename/actions/runs/11658829460/job/32458444391), so everything is great. :-)

Merged as d5dca9242d7df401db8eb13fa09cf8606e12bb2e. Thank you again!

2024-11-04 05:57 UTC, closed without merging

2024-11-04 08:08 UTC, cdown commented
1.1.0 released to crates.io with this feature. Thanks!